train_index:
  - 0
  - 1
  - 2
test_index:
  - 3
dset_path: data/small_particle_data/graphite
augmentation_path: configs/augmentations/small_particle_graphite.py
activation: sigmoid
device: cuda
bs:
  train: 3
  test: 1
architecture: Unet
encoder: vgg11
output_path: models/graphite
lr: 0.0001
n_epochs: 500
print_every: 50
lr_reduce_epochs:
  - 200
  - 400
lr_reduce_by: 10